export const defaultTasks = [
    {
        board: "opened",
        body: "The drag overlay is not rendered in a portal by default. Rather, it is rendered in the container where it is rendered. ",
        expDate: 1717200000000,
        id: "p8luerd",
        projectId: "vp6lz9p",
        title: "Portals",
    },
    {
        board: "opened",
        body: "Depending on your use-case, you may want to use a drag overlay rather than transforming the original draggable source element that is connected to the useDraggable hook:",
        expDate: 1717286400000,
        id: "jouo4qe",
        projectId: "vp6lz9p",
        title: "Drop animation",
    },
    {
        board: "opened",
        body: "You may also nest <DndContext> providers within other <DndContext> providers to achieve nested draggable/droppable interfaces that are independent of one another.",
        expDate: 1717804800000,
        id: "mzfx1m1",
        projectId: "18xpdsv",
        title: "Nesting",
    },
    {
        board: "inProcess",
        body: "For example, you can use modifiers to restrict the movement of the <DragOverlay> to the bounds of the window:",
        expDate: 1717545600000,
        id: "clik7a9",
        projectId: "vp6lz9p",
        title: "Modifiers",
    },
    {
        board: "inProcess",
        body: "The zIndex prop sets the z-order of the drag overlay. The default value is 999 for compatibility reasons, but we highly recommend you use a lower value. ",
        expDate: 1717545600000,
        id: "pela8a6",
        projectId: "vp6lz9p",
        title: "Wrapper element",
    },
    {
        board: "inProcess",
        body: "If you want smooth drop animations without the effort of building them yourself.",
        expDate: 1717200000000,
        id: "oktqpdw",
        projectId: "vp6lz9p",
        title: "Drag Overlay",
    },
];
